import type { BudgetProposal } from '@/types/budgeting';

export const TOTAL_TOKENS_PER_USER = 5;

export const INITIAL_PROPOSALS: BudgetProposal[] = [
  {
    id: 'hel-library-hub',
    municipalityId: 'helsinki',
    titleKey: 'budgeting.proposals.hel_library_hub.title',
    descriptionKey: 'budgeting.proposals.hel_library_hub.description',
    category: 'culture_events',
    requiredBudget: 45000,
    district: 'Keskusta / Oodi',
    votesCount: 842,
    targetVotes: 1000,
    submittedBy: 'Helsinki Expat Readers & Tech Guild',
    status: 'active',
  },
  {
    id: 'hel-language-cafes',
    municipalityId: 'helsinki',
    titleKey: 'budgeting.proposals.hel_language_cafes.title',
    descriptionKey: 'budgeting.proposals.hel_language_cafes.description',
    category: 'integration_language',
    requiredBudget: 15000,
    district: 'Kallio & Pasila',
    votesCount: 1180,
    targetVotes: 1000,
    submittedBy: 'Kotoutumisverkosto ry',
    status: 'funded',
  },
  {
    id: 'tam-winter-sauna',
    municipalityId: 'tampere',
    titleKey: 'budgeting.proposals.tam_winter_sauna.title',
    descriptionKey: 'budgeting.proposals.tam_winter_sauna.description',
    category: 'sports_outdoor',
    requiredBudget: 35000,
    district: 'Pyynikki / Näsijärvi',
    votesCount: 620,
    targetVotes: 800,
    submittedBy: 'Tampere International Sauna Society',
    status: 'active',
  },
  {
    id: 'tam-esports-academy',
    municipalityId: 'tampere',
    titleKey: 'budgeting.proposals.tam_esports_academy.title',
    descriptionKey: 'budgeting.proposals.tam_esports_academy.description',
    category: 'children_youth',
    requiredBudget: 28000,
    district: 'Hervanta',
    votesCount: 510,
    targetVotes: 600,
    submittedBy: 'Hervanta Youth Gaming Lab',
    status: 'active',
  },
  {
    id: 'esp-nature-trails',
    municipalityId: 'espoo',
    titleKey: 'budgeting.proposals.esp_nature_trails.title',
    descriptionKey: 'budgeting.proposals.esp_nature_trails.description',
    category: 'environment_parks',
    requiredBudget: 18000,
    district: 'Nuuksio & Otaniemi Waterfront',
    votesCount: 780,
    targetVotes: 800,
    submittedBy: 'Espoo Outdoor & Expat Hikers',
    status: 'active',
  },
  {
    id: 'oul-bike-stations',
    municipalityId: 'oulu',
    titleKey: 'budgeting.proposals.oul_bike_stations.title',
    descriptionKey: 'budgeting.proposals.oul_bike_stations.description',
    category: 'cycling_transit',
    requiredBudget: 20000,
    district: 'Linnanmaa & City Centre',
    votesCount: 940,
    targetVotes: 900,
    submittedBy: 'Oulu Winter Cycling Advocates',
    status: 'funded',
  },
  {
    id: 'tur-river-festival',
    municipalityId: 'turku',
    titleKey: 'budgeting.proposals.tur_river_festival.title',
    descriptionKey: 'budgeting.proposals.tur_river_festival.description',
    category: 'culture_events',
    requiredBudget: 25000,
    district: 'Aurajoki Riverbanks',
    votesCount: 430,
    targetVotes: 700,
    submittedBy: 'Turku International Culture Association',
    status: 'active',
  },
  {
    id: 'van-community-garden',
    municipalityId: 'vantaa',
    titleKey: 'budgeting.proposals.van_community_garden.title',
    descriptionKey: 'budgeting.proposals.van_community_garden.description',
    category: 'environment_parks',
    requiredBudget: 22000,
    district: 'Tikkurila',
    votesCount: 590,
    targetVotes: 700,
    submittedBy: 'Vantaa Multicultural Family Gardeners',
    status: 'active',
  },
];
