import type { CommunityEvent, NoticeBoardPost, MentorProfile } from '@/types/community';

export const INITIAL_COMMUNITY_EVENTS: CommunityEvent[] = [
  {
    id: 'event-1',
    municipalityId: 'helsinki',
    title: 'Oodi Multilingual Language Cafe & Board Games',
    description: 'Casual weekly meetup to practice conversational Finnish, Swedish, and English while playing Finnish board games (Alias, Afrikan Tähti, Carcassonne). All levels welcome from A1 to fluent!',
    category: 'language_exchange',
    date: '2026-09-12',
    time: '17:30 - 19:30',
    location: 'Central Library Oodi (2nd Floor, Urban Workshop), Töölönlahdenkatu 4',
    organizer: 'Helsinki City Library & Helsinki Expat Club',
    attendeesCount: 38,
    maxAttendees: 50,
    languages: ['Finnish', 'English', 'Swedish'],
    price: 'Free',
  },
  {
    id: 'event-2',
    municipalityId: 'espoo',
    title: 'Nuuksio National Park Autumn Hike & Sausage Grill',
    description: 'Family-friendly guided nature trail walk (approx. 6 km) around Lake Pitkäjärvi followed by traditional camp-fire sausage grilling and blueberry tea. Learn everyman’s rights (jokamiehenoikeus)!',
    category: 'sports_outdoor',
    date: '2026-09-19',
    time: '11:00 - 15:00',
    location: 'Haltia Nature Centre Entrance, Nuuksiontie 84, Espoo',
    organizer: 'Espoo Sports & Youth Services',
    attendeesCount: 42,
    maxAttendees: 60,
    languages: ['English', 'Finnish'],
    price: 'Free',
  },
  {
    id: 'event-3',
    municipalityId: 'tampere',
    title: 'International Sauna & Avanto Ice-Dipping Evening',
    description: 'Experience authentic Finnish sauna culture at historic Rauhaniemi sauna on the shores of Lake Näsijärvi. Includes introductory sauna etiquette talk for international newcomers.',
    category: 'cultural',
    date: '2026-09-23',
    time: '18:00 - 20:30',
    location: 'Rauhaniemen Kansankylpylä, Rauhaniementie 24, Tampere',
    organizer: 'International House Tampere Community',
    attendeesCount: 28,
    maxAttendees: 35,
    languages: ['English', 'Finnish', 'Ukrainian'],
    price: '€9 (Sauna entry ticket)',
  },
  {
    id: 'event-4',
    municipalityId: 'vantaa',
    title: 'Expat Parents & Toddlers Playgroup at Tiedekeskus Heureka',
    description: 'Weekly morning playgroup for international parents on parental leave. Safe indoor exploration area, coffee corner, and peer networking on daycare enrollment in Vantaa.',
    category: 'family',
    date: '2026-09-16',
    time: '10:00 - 12:00',
    location: 'Heureka Science Park, Kuninkaalantie 7, Tikkurila',
    organizer: 'Vantaa Immigrant Family Services',
    attendeesCount: 19,
    maxAttendees: 30,
    languages: ['English', 'Finnish', 'Russian'],
    price: 'Free entry for parents and under-3s',
  },
  {
    id: 'event-5',
    municipalityId: 'oulu',
    title: 'Winter Cycling Masterclass & Studded Tire Clinic',
    description: 'Learn how to ride year-round safely in the winter cycling capital of the world. Demonstration on dressing for sub-zero weather, tire changing, and bike maintenance in snow.',
    category: 'sports_outdoor',
    date: '2026-09-26',
    time: '14:00 - 16:30',
    location: 'Rotuaari Square & BusinessAsema, Hallituskatu 36, Oulu',
    organizer: 'Oulu Cycling Association & City of Oulu',
    attendeesCount: 55,
    languages: ['English', 'Finnish'],
    price: 'Free',
  },
  {
    id: 'event-6',
    municipalityId: 'turku',
    title: 'International Tech & Creative Founders After-Work',
    description: 'Informal networking for immigrant founders, tech engineers, and creative freelancers across Southwest Finland. Short pitches followed by drinks and networking.',
    category: 'networking',
    date: '2026-09-24',
    time: '18:00 - 21:00',
    location: 'SparkUp Turku, Tykistökatu 4B (ElectroCity), Turku',
    organizer: 'Turku Science Park & International House Turku',
    attendeesCount: 64,
    maxAttendees: 80,
    languages: ['English'],
    price: 'Free (Refreshments provided)',
  },
];

export const INITIAL_NOTICES: NoticeBoardPost[] = [
  {
    id: 'notice-1',
    municipalityId: 'helsinki',
    author: 'Maria S.',
    title: 'YKI Finnish B1 Test Study Group - Seeking 2 Partners',
    content: 'Studying for the upcoming November YKI test. Looking for 2 people in Helsinki to meet twice a week at Pasila library to practice speaking and essay structures together.',
    category: 'study_buddy',
    createdAt: '2026-09-05T14:00:00Z',
    contact: 'maria.studies.yki@example.com',
  },
  {
    id: 'notice-2',
    municipalityId: 'espoo',
    author: 'Johan B.',
    title: 'Free Children’s Wooden High Chair & Stroller Giveaway',
    content: 'Our toddler has grown out of the Stokke Tripp Trapp chair and Emmaljunga stroller. In great condition, free for any newly arrived family who needs it. Pick up in Tapiola.',
    category: 'goods_giveaway',
    createdAt: '2026-09-04T10:30:00Z',
    contact: 'johan.tapiola@example.com',
  },
  {
    id: 'notice-3',
    municipalityId: 'tampere',
    author: 'Elena & Andrei',
    title: 'Roommate wanted in spacious 3-room apartment near TAMK / TAYS',
    content: 'Furnished private bedroom (18m²) in a clean, quiet 85m² flat in Kauppi. Close to forest trails and tram line 1. Rent €420/month including 1 Gbps fiber internet and water.',
    category: 'housing_sharing',
    createdAt: '2026-09-06T18:15:00Z',
    contact: 'kauppi.flatshare@example.com',
  },
  {
    id: 'notice-4',
    municipalityId: 'turku',
    author: 'Kenji T.',
    title: 'Japanese - Finnish / English conversational exchange',
    content: 'Native Japanese speaker working at Turku shipyard. Seeking a conversational partner for casual Finnish language practice over coffee. Happy to teach Japanese or talk anime/history.',
    category: 'study_buddy',
    createdAt: '2026-09-02T12:00:00Z',
    contact: 'kenji.shipyard@example.com',
  },
  {
    id: 'notice-5',
    municipalityId: 'oulu',
    author: 'Priya N.',
    title: 'Winter clothing advice & winter boot recommendations for beginners',
    content: 'Moved here recently from India with 2 school-aged kids. Looking for advice on which second-hand shops (Kierrätyskeskus / Kirpputori) in Oulu are best for Gore-Tex winter overalls and thermal layers.',
    category: 'advice',
    createdAt: '2026-09-07T09:45:00Z',
    contact: 'priya.oulu@example.com',
  },
];

export const INITIAL_MENTORS: MentorProfile[] = [
  {
    id: 'mentor-1',
    municipalityId: 'helsinki',
    name: 'Liisa Thorne',
    originCountry: 'United Kingdom',
    yearsInFinland: 8,
    profession: 'Senior Product Manager @ Supercell',
    languages: ['English', 'Finnish (Fluent C1)'],
    bio: 'Moved to Helsinki in 2018. Navigated permanent residency, buying an apartment (asunto-osake), and schooling for 2 kids. Passionate about helping new arrivals thrive in Finnish tech.',
    specialties: ['Tech Careers', 'Apartment Buying', 'Permanent Residency (PR)'],
    contactEmail: 'liisa.thorne.mentor@example.com',
  },
  {
    id: 'mentor-2',
    municipalityId: 'espoo',
    name: 'Alexei Voronov',
    originCountry: 'Estonia / Ukraine',
    yearsInFinland: 6,
    profession: 'Software Architect & Cloud Specialist',
    languages: ['Russian', 'Ukrainian', 'English', 'Finnish (B2)'],
    bio: 'Relocated via specialist visa, now a Finnish citizen. Experienced with Vero tax cards, deduction maximization (kotitalousvähennys), and YKI examination preparation.',
    specialties: ['Vero Tax Optimization', 'YKI Test Prep', 'Citizenship Application'],
    contactEmail: 'alexei.v.mentor@example.com',
  },
  {
    id: 'mentor-3',
    municipalityId: 'tampere',
    name: 'Fatima Al-Mansoor',
    originCountry: 'Jordan',
    yearsInFinland: 4,
    profession: 'Data Analyst & Researcher at Tampere University',
    languages: ['Arabic', 'English', 'Finnish (B1)'],
    bio: 'Assists international students and researchers settling in Pirkanmaa. Expert in student residence permits, Kela student benefits, and finding rental housing in Tampere.',
    specialties: ['University Studies', 'Kela Support', 'Family Relocation'],
    contactEmail: 'fatima.m.mentor@example.com',
  },
  {
    id: 'mentor-4',
    municipalityId: 'oulu',
    name: 'Mikko Chen',
    originCountry: 'Taiwan',
    yearsInFinland: 11,
    profession: 'Hardware Engineer & Serial Entrepreneur',
    languages: ['Mandarin', 'English', 'Finnish (C1)'],
    bio: '11 winters in northern Finland! Successfully founded two hardware startups in Oulu. Happy to advise newcomers on surviving sub-zero winters, winter biking, and business incubation.',
    specialties: ['Winter Survival & Biking', 'Startup Grants (Starttiraha)', 'Networking in Oulu'],
    contactEmail: 'mikko.chen.mentor@example.com',
  },
  {
    id: 'mentor-5',
    municipalityId: 'turku',
    name: 'Clara Dubois',
    originCountry: 'France',
    yearsInFinland: 5,
    profession: 'Biotech Lab Coordinator @ University of Turku',
    languages: ['French', 'English', 'Swedish (B1)', 'Finnish (A2)'],
    bio: 'Living in bilingual Turku/Åbo. Can advise on navigating bilingual services in Southwest Finland, daycares, healthcare centers (terveysasemat), and local expat networks.',
    specialties: ['Healthcare Navigation', 'Bilingual Swedish/Finnish Services', 'Daycare Registration'],
    contactEmail: 'clara.dubois.mentor@example.com',
  },
];
