import type { MunicipalityId } from '@/types/onboarding';
import type { MunicipalCityDataset } from '@/types/municipalAnalytics';

export const MUNICIPAL_DATASETS: Record<MunicipalityId, MunicipalCityDataset> = {
  helsinki: {
    municipalityId: 'helsinki',
    cityName: 'Helsinki',
    populationTotal: 114800,
    kpi: {
      totalExpats: 114800,
      monthlyGrowthPercent: 8.4,
      avgIntegrationProgress: 68,
      specialistsRate: 64,
      familiesWithKidsPercent: 38,
      satisfactionIndex: 4.2,
    },
    skills: [
      { name: 'Software & Cloud Engineering', count: 36700, percentage: 32, localDemand: 'critical', topIndustry: 'IT & SaaS' },
      { name: 'AI & Data Science', count: 21800, percentage: 19, localDemand: 'critical', topIndustry: 'DeepTech & Finance' },
      { name: 'Fintech & Banking', count: 17200, percentage: 15, localDemand: 'high', topIndustry: 'Financial Services' },
      { name: 'Game Design & Graphics', count: 16100, percentage: 14, localDemand: 'high', topIndustry: 'Creative Industries' },
      { name: 'Healthcare & Nursing', count: 12600, percentage: 11, localDemand: 'critical', topIndustry: 'Health & Wellbeing' },
      { name: 'CleanTech & Energy', count: 10400, percentage: 9, localDemand: 'moderate', topIndustry: 'Sustainability' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri', completionRate: 94, avgProcessingDays: 32, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'DVV / IHH', completionRate: 88, avgProcessingDays: 16, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Commercial Banks', completionRate: 61, avgProcessingDays: 28, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela', completionRate: 74, avgProcessingDays: 22, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Private / Municipal', completionRate: 82, avgProcessingDays: 24, benchmarkDays: 14, severity: 'warning', insightKey: 'analytics.insights.housing_cost' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Helsinki (eVaka)', completionRate: 58, avgProcessingDays: 52, benchmarkDays: 40, severity: 'warning', insightKey: 'analytics.insights.daycare_spots' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Työväenopisto / TE', completionRate: 46, avgProcessingDays: 60, benchmarkDays: 45, severity: 'warning', insightKey: 'analytics.insights.language_capacity' },
    ],
    demographics: {
      citizenship: { eu: 44, nordic: 6, nonEu: 50 },
      topNationalities: [
        { country: 'India', count: 18300, percentage: 16 },
        { country: 'Ukraine', count: 14900, percentage: 13 },
        { country: 'Estonia', count: 13800, percentage: 12 },
        { country: 'Germany / UK', count: 11500, percentage: 10 },
        { country: 'China', count: 8000, percentage: 7 },
      ],
      nativeLanguages: [
        { language: 'English', percentage: 38 },
        { language: 'Russian / Ukrainian', percentage: 24 },
        { language: 'Hindi / Indian Languages', percentage: 14 },
        { language: 'Spanish / French', percentage: 11 },
        { language: 'Others', percentage: 13 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 31 },
        { range: '30-39', percentage: 46 },
        { range: '40-49', percentage: 16 },
        { range: '50+', percentage: 7 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.2,
      totalSurveyResponses: 3840,
      topPainPoints: [
        { issueKey: 'analytics.pain.bank_friction', count: 1420, severity: 'high' },
        { issueKey: 'analytics.pain.housing_affordability', count: 1150, severity: 'high' },
        { issueKey: 'analytics.pain.language_barrier_jobs', count: 890, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.public_transport', count: 2180 },
        { factorKey: 'analytics.attract.child_safety', count: 1940 },
        { factorKey: 'analytics.attract.tech_scene', count: 1630 },
      ],
    },
  },

  espoo: {
    municipalityId: 'espoo',
    cityName: 'Espoo',
    populationTotal: 62400,
    kpi: {
      totalExpats: 62400,
      monthlyGrowthPercent: 9.1,
      avgIntegrationProgress: 71,
      specialistsRate: 72,
      familiesWithKidsPercent: 52,
      satisfactionIndex: 4.4,
    },
    skills: [
      { name: 'Telecom & 5G/6G', count: 24300, percentage: 39, localDemand: 'critical', topIndustry: 'Nokia / DeepTech' },
      { name: 'Software & Cloud', count: 16800, percentage: 27, localDemand: 'critical', topIndustry: 'Otaniemi Tech Hub' },
      { name: 'CleanTech & Quantum', count: 9900, percentage: 16, localDemand: 'high', topIndustry: 'VTT & Aalto Science' },
      { name: 'Product Management', count: 6200, percentage: 10, localDemand: 'moderate', topIndustry: 'Enterprise Tech' },
      { name: 'Biotech & Health', count: 5200, percentage: 8, localDemand: 'moderate', topIndustry: 'Life Sciences' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri', completionRate: 96, avgProcessingDays: 28, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'DVV / IHH', completionRate: 91, avgProcessingDays: 14, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Commercial Banks', completionRate: 64, avgProcessingDays: 25, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela', completionRate: 78, avgProcessingDays: 20, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Private / Housing', completionRate: 85, avgProcessingDays: 21, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_normal' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Espoo (eVaka)', completionRate: 54, avgProcessingDays: 58, benchmarkDays: 40, severity: 'critical', insightKey: 'analytics.insights.daycare_spots' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Arbis / Omnia', completionRate: 49, avgProcessingDays: 55, benchmarkDays: 45, severity: 'warning', insightKey: 'analytics.insights.language_capacity' },
    ],
    demographics: {
      citizenship: { eu: 41, nordic: 5, nonEu: 54 },
      topNationalities: [
        { country: 'India', count: 12500, percentage: 20 },
        { country: 'China', count: 7500, percentage: 12 },
        { country: 'Ukraine', count: 6800, percentage: 11 },
        { country: 'Estonia', count: 5600, percentage: 9 },
        { country: 'Germany / France', count: 5000, percentage: 8 },
      ],
      nativeLanguages: [
        { language: 'English', percentage: 42 },
        { language: 'Russian / Ukrainian', percentage: 21 },
        { language: 'Hindi / Telugu', percentage: 18 },
        { language: 'Chinese', percentage: 9 },
        { language: 'Others', percentage: 10 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 24 },
        { range: '30-39', percentage: 53 },
        { range: '40-49', percentage: 18 },
        { range: '50+', percentage: 5 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.4,
      totalSurveyResponses: 2190,
      topPainPoints: [
        { issueKey: 'analytics.pain.daycare_queues', count: 870, severity: 'high' },
        { issueKey: 'analytics.pain.bank_friction', count: 780, severity: 'high' },
        { issueKey: 'analytics.pain.spouse_employment', count: 620, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.nature_closeness', count: 1540 },
        { factorKey: 'analytics.attract.tech_ecosystem', count: 1410 },
        { factorKey: 'analytics.attract.international_schools', count: 1280 },
      ],
    },
  },

  tampere: {
    municipalityId: 'tampere',
    cityName: 'Tampere',
    populationTotal: 24500,
    kpi: {
      totalExpats: 24500,
      monthlyGrowthPercent: 11.2,
      avgIntegrationProgress: 65,
      specialistsRate: 61,
      familiesWithKidsPercent: 32,
      satisfactionIndex: 4.5,
    },
    skills: [
      { name: 'Gaming & Interactive Media', count: 7800, percentage: 32, localDemand: 'critical', topIndustry: 'Game Studios' },
      { name: 'Intelligent Machinery & Robotics', count: 6400, percentage: 26, localDemand: 'critical', topIndustry: 'Manufacturing Tech' },
      { name: 'Embedded Systems & IoT', count: 4900, percentage: 20, localDemand: 'high', topIndustry: 'Industrial Automation' },
      { name: 'Optics & Photonics', count: 2900, percentage: 12, localDemand: 'high', topIndustry: 'Laser & DeepTech' },
      { name: 'Health & MedTech', count: 2500, percentage: 10, localDemand: 'moderate', topIndustry: 'TAYS / Tampere Bio' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri Tampere', completionRate: 93, avgProcessingDays: 30, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'IH Tampere', completionRate: 86, avgProcessingDays: 15, benchmarkDays: 10, severity: 'normal', insightKey: 'analytics.insights.dvv_tampere' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Local Banks', completionRate: 59, avgProcessingDays: 31, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela Pirkanmaa', completionRate: 72, avgProcessingDays: 23, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Tampere Rentals', completionRate: 89, avgProcessingDays: 16, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_tampere' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Tampere (eVaka)', completionRate: 66, avgProcessingDays: 44, benchmarkDays: 40, severity: 'normal', insightKey: 'analytics.insights.daycare_normal' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Tampereen seudun työväenopisto', completionRate: 52, avgProcessingDays: 48, benchmarkDays: 45, severity: 'normal', insightKey: 'analytics.insights.language_tampere' },
    ],
    demographics: {
      citizenship: { eu: 48, nordic: 4, nonEu: 48 },
      topNationalities: [
        { country: 'Ukraine', count: 3900, percentage: 16 },
        { country: 'India', count: 3400, percentage: 14 },
        { country: 'Spain / Italy', count: 2700, percentage: 11 },
        { country: 'Germany', count: 2450, percentage: 10 },
        { country: 'China', count: 1950, percentage: 8 },
      ],
      nativeLanguages: [
        { language: 'English', percentage: 36 },
        { language: 'Spanish / Southern European', percentage: 22 },
        { language: 'Russian / Ukrainian', percentage: 19 },
        { language: 'Others', percentage: 23 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 38 },
        { range: '30-39', percentage: 44 },
        { range: '40-49', percentage: 13 },
        { range: '50+', percentage: 5 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.5,
      totalSurveyResponses: 1120,
      topPainPoints: [
        { issueKey: 'analytics.pain.bank_friction', count: 480, severity: 'high' },
        { issueKey: 'analytics.pain.direct_flight_connections', count: 390, severity: 'medium' },
        { issueKey: 'analytics.pain.spouse_employment', count: 310, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.compact_walkable_city', count: 890 },
        { factorKey: 'analytics.attract.sauna_and_lakes', count: 820 },
        { factorKey: 'analytics.attract.vibrant_game_community', count: 760 },
      ],
    },
  },

  oulu: {
    municipalityId: 'oulu',
    cityName: 'Oulu',
    populationTotal: 13800,
    kpi: {
      totalExpats: 13800,
      monthlyGrowthPercent: 7.6,
      avgIntegrationProgress: 62,
      specialistsRate: 68,
      familiesWithKidsPercent: 35,
      satisfactionIndex: 4.1,
    },
    skills: [
      { name: 'Wireless & Radio Systems', count: 5400, percentage: 39, localDemand: 'critical', topIndustry: '6G Flagship & Nokia' },
      { name: 'Embedded Software & IoT', count: 3700, percentage: 27, localDemand: 'critical', topIndustry: 'Automotive & Hardware' },
      { name: 'HealthTech & Biosensors', count: 2100, percentage: 15, localDemand: 'high', topIndustry: 'OuluHealth' },
      { name: 'Printed Electronics', count: 1400, percentage: 10, localDemand: 'high', topIndustry: 'VTT & Polar Bear Tech' },
      { name: 'Game & XR Development', count: 1200, percentage: 9, localDemand: 'moderate', topIndustry: 'Oulu Game LAB' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri Oulu', completionRate: 91, avgProcessingDays: 34, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'IH Oulu', completionRate: 83, avgProcessingDays: 17, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Local Banks', completionRate: 57, avgProcessingDays: 33, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela Pohjois-Pohjanmaa', completionRate: 70, avgProcessingDays: 24, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Oulu Housing', completionRate: 92, avgProcessingDays: 14, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_oulu' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Oulu', completionRate: 64, avgProcessingDays: 42, benchmarkDays: 40, severity: 'normal', insightKey: 'analytics.insights.daycare_normal' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Oulu-opisto', completionRate: 44, avgProcessingDays: 62, benchmarkDays: 45, severity: 'warning', insightKey: 'analytics.insights.language_capacity' },
    ],
    demographics: {
      citizenship: { eu: 38, nordic: 5, nonEu: 57 },
      topNationalities: [
        { country: 'India', count: 3200, percentage: 23 },
        { country: 'Ukraine', count: 2100, percentage: 15 },
        { country: 'China', count: 1800, percentage: 13 },
        { country: 'Pakistan / Bangladesh', count: 1400, percentage: 10 },
        { country: 'EU / Others', count: 5300, percentage: 39 },
      ],
      nativeLanguages: [
        { language: 'English', percentage: 41 },
        { language: 'Hindi / Urdu', percentage: 22 },
        { language: 'Russian / Ukrainian', percentage: 17 },
        { language: 'Chinese', percentage: 11 },
        { language: 'Others', percentage: 9 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 35 },
        { range: '30-39', percentage: 48 },
        { range: '40-49', percentage: 12 },
        { range: '50+', percentage: 5 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.1,
      totalSurveyResponses: 830,
      topPainPoints: [
        { issueKey: 'analytics.pain.winter_adaptation', count: 420, severity: 'high' },
        { issueKey: 'analytics.pain.bank_friction', count: 390, severity: 'high' },
        { issueKey: 'analytics.pain.distance_from_capital', count: 260, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.safe_for_families', count: 640 },
        { factorKey: 'analytics.attract.winter_cycling_infrastructure', count: 580 },
        { factorKey: 'analytics.attract.world_class_wireless_hub', count: 520 },
      ],
    },
  },

  turku: {
    municipalityId: 'turku',
    cityName: 'Turku',
    populationTotal: 23100,
    kpi: {
      totalExpats: 23100,
      monthlyGrowthPercent: 8.1,
      avgIntegrationProgress: 66,
      specialistsRate: 54,
      familiesWithKidsPercent: 36,
      satisfactionIndex: 4.3,
    },
    skills: [
      { name: 'Marine Tech & Shipbuilding', count: 6900, percentage: 30, localDemand: 'critical', topIndustry: 'Meyer Turku & Maritime' },
      { name: 'Biotech & Pharma', count: 5800, percentage: 25, localDemand: 'critical', topIndustry: 'Turku Science Park' },
      { name: 'Software Development', count: 4600, percentage: 20, localDemand: 'high', topIndustry: 'IT & Digital Services' },
      { name: 'Chemical Engineering', count: 3200, percentage: 14, localDemand: 'high', topIndustry: 'Materials & Chemistry' },
      { name: 'Design & Hospitality', count: 2600, percentage: 11, localDemand: 'moderate', topIndustry: 'Tourism & Culture' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri Turku', completionRate: 92, avgProcessingDays: 31, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'IH Turku', completionRate: 85, avgProcessingDays: 16, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Local Banks', completionRate: 60, avgProcessingDays: 29, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela Varsinais-Suomi', completionRate: 73, avgProcessingDays: 22, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Turku Housing', completionRate: 88, avgProcessingDays: 18, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_turku' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Turku', completionRate: 63, avgProcessingDays: 45, benchmarkDays: 40, severity: 'normal', insightKey: 'analytics.insights.daycare_normal' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Turun suomenkielinen työväenopisto', completionRate: 50, avgProcessingDays: 52, benchmarkDays: 45, severity: 'normal', insightKey: 'analytics.insights.language_turku' },
    ],
    demographics: {
      citizenship: { eu: 52, nordic: 6, nonEu: 42 },
      topNationalities: [
        { country: 'Ukraine', count: 3700, percentage: 16 },
        { country: 'Poland / Baltic', count: 3200, percentage: 14 },
        { country: 'India', count: 2800, percentage: 12 },
        { country: 'Germany / Sweden', count: 2500, percentage: 11 },
        { country: 'Others', count: 10900, percentage: 47 },
      ],
      nativeLanguages: [
        { language: 'English', percentage: 34 },
        { language: 'Russian / Ukrainian', percentage: 22 },
        { language: 'Polish / Slavic', percentage: 16 },
        { language: 'Swedish', percentage: 12 },
        { language: 'Others', percentage: 16 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 34 },
        { range: '30-39', percentage: 45 },
        { range: '40-49', percentage: 15 },
        { range: '50+', percentage: 6 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.3,
      totalSurveyResponses: 980,
      topPainPoints: [
        { issueKey: 'analytics.pain.bank_friction', count: 410, severity: 'high' },
        { issueKey: 'analytics.pain.bilingual_demands', count: 340, severity: 'medium' },
        { issueKey: 'analytics.pain.housing_affordability', count: 280, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.archipelago_nature', count: 740 },
        { factorKey: 'analytics.attract.rich_cultural_heritage', count: 680 },
        { factorKey: 'analytics.attract.compact_bicycle_friendly', count: 620 },
      ],
    },
  },

  vantaa: {
    municipalityId: 'vantaa',
    cityName: 'Vantaa',
    populationTotal: 58200,
    kpi: {
      totalExpats: 58200,
      monthlyGrowthPercent: 9.8,
      avgIntegrationProgress: 64,
      specialistsRate: 48,
      familiesWithKidsPercent: 46,
      satisfactionIndex: 4.1,
    },
    skills: [
      { name: 'Logistics & Supply Chain', count: 17500, percentage: 30, localDemand: 'critical', topIndustry: 'Helsinki Airport & Freight' },
      { name: 'Aviation & Aerotech', count: 11600, percentage: 20, localDemand: 'critical', topIndustry: 'Airport City' },
      { name: 'Construction & Civil Engineering', count: 9900, percentage: 17, localDemand: 'high', topIndustry: 'Infrastructure' },
      { name: 'IT Support & Operations', count: 9300, percentage: 16, localDemand: 'high', topIndustry: 'Enterprise Services' },
      { name: 'Food Technology & Production', count: 9900, percentage: 17, localDemand: 'moderate', topIndustry: 'Manufacturing' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri', completionRate: 94, avgProcessingDays: 31, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'DVV / International Vantaa', completionRate: 87, avgProcessingDays: 16, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Commercial Banks', completionRate: 58, avgProcessingDays: 30, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela Vantaa', completionRate: 75, avgProcessingDays: 21, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Vantaa Housing', completionRate: 86, avgProcessingDays: 19, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_vantaa' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'City of Vantaa (eVaka)', completionRate: 61, avgProcessingDays: 48, benchmarkDays: 40, severity: 'warning', insightKey: 'analytics.insights.daycare_spots' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Vantaan aikuisopisto', completionRate: 48, avgProcessingDays: 56, benchmarkDays: 45, severity: 'warning', insightKey: 'analytics.insights.language_capacity' },
    ],
    demographics: {
      citizenship: { eu: 46, nordic: 4, nonEu: 50 },
      topNationalities: [
        { country: 'Estonia', count: 12800, percentage: 22 },
        { country: 'Ukraine', count: 8700, percentage: 15 },
        { country: 'India', count: 5800, percentage: 10 },
        { country: 'Vietnam / Philippines', count: 5200, percentage: 9 },
        { country: 'Others', count: 25700, percentage: 44 },
      ],
      nativeLanguages: [
        { language: 'Russian / Ukrainian', percentage: 29 },
        { language: 'Estonian', percentage: 22 },
        { language: 'English', percentage: 24 },
        { language: 'Others', percentage: 25 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 28 },
        { range: '30-39', percentage: 49 },
        { range: '40-49', percentage: 16 },
        { range: '50+', percentage: 7 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.1,
      totalSurveyResponses: 1980,
      topPainPoints: [
        { issueKey: 'analytics.pain.bank_friction', count: 790, severity: 'high' },
        { issueKey: 'analytics.pain.language_barrier_jobs', count: 640, severity: 'high' },
        { issueKey: 'analytics.pain.daycare_queues', count: 510, severity: 'medium' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.airport_proximity', count: 1420 },
        { factorKey: 'analytics.attract.affordable_housing_vs_helsinki', count: 1250 },
        { factorKey: 'analytics.attract.multicultural_schools', count: 980 },
      ],
    },
  },

  other: {
    municipalityId: 'other',
    cityName: 'National Average / Other Municipalities',
    populationTotal: 45000,
    kpi: {
      totalExpats: 45000,
      monthlyGrowthPercent: 6.2,
      avgIntegrationProgress: 60,
      specialistsRate: 45,
      familiesWithKidsPercent: 40,
      satisfactionIndex: 4.0,
    },
    skills: [
      { name: 'Agriculture & Bioeconomy', count: 11200, percentage: 25, localDemand: 'critical', topIndustry: 'Primary Production' },
      { name: 'Industrial Manufacturing', count: 9900, percentage: 22, localDemand: 'critical', topIndustry: 'Heavy Industry' },
      { name: 'Healthcare & Elderly Care', count: 9000, percentage: 20, localDemand: 'critical', topIndustry: 'Wellbeing Services' },
      { name: 'Tourism & Seasonal Work', count: 8100, percentage: 18, localDemand: 'high', topIndustry: 'Lapland / Lakeland' },
      { name: 'IT & Remote Work', count: 6800, percentage: 15, localDemand: 'moderate', topIndustry: 'Remote Work' },
    ],
    funnel: [
      { id: 'migri', titleKey: 'analytics.funnel.migri', department: 'Migri', completionRate: 90, avgProcessingDays: 35, benchmarkDays: 30, severity: 'normal', insightKey: 'analytics.insights.migri_normal' },
      { id: 'dvv', titleKey: 'analytics.funnel.dvv', department: 'Regional DVV', completionRate: 81, avgProcessingDays: 18, benchmarkDays: 10, severity: 'warning', insightKey: 'analytics.insights.dvv_queue' },
      { id: 'bank', titleKey: 'analytics.funnel.bank', department: 'Local Banks', completionRate: 54, avgProcessingDays: 34, benchmarkDays: 7, severity: 'critical', insightKey: 'analytics.insights.bank_delay' },
      { id: 'kela', titleKey: 'analytics.funnel.kela', department: 'Kela', completionRate: 69, avgProcessingDays: 24, benchmarkDays: 21, severity: 'normal', insightKey: 'analytics.insights.kela_normal' },
      { id: 'housing', titleKey: 'analytics.funnel.housing', department: 'Municipal Rentals', completionRate: 90, avgProcessingDays: 15, benchmarkDays: 14, severity: 'normal', insightKey: 'analytics.insights.housing_normal' },
      { id: 'daycare', titleKey: 'analytics.funnel.daycare', department: 'Local Daycare', completionRate: 68, avgProcessingDays: 38, benchmarkDays: 40, severity: 'normal', insightKey: 'analytics.insights.daycare_normal' },
      { id: 'language', titleKey: 'analytics.funnel.language', department: 'Kansalaisopisto', completionRate: 42, avgProcessingDays: 65, benchmarkDays: 45, severity: 'warning', insightKey: 'analytics.insights.language_capacity' },
    ],
    demographics: {
      citizenship: { eu: 55, nordic: 5, nonEu: 40 },
      topNationalities: [
        { country: 'Ukraine', count: 11000, percentage: 24 },
        { country: 'Estonia', count: 8500, percentage: 19 },
        { country: 'Poland', count: 5400, percentage: 12 },
        { country: 'Others', count: 20100, percentage: 45 },
      ],
      nativeLanguages: [
        { language: 'Russian / Ukrainian', percentage: 34 },
        { language: 'English', percentage: 28 },
        { language: 'Estonian', percentage: 19 },
        { language: 'Others', percentage: 19 },
      ],
      ageGroups: [
        { range: '20-29', percentage: 29 },
        { range: '30-39', percentage: 47 },
        { range: '40-49', percentage: 17 },
        { range: '50+', percentage: 7 },
      ],
    },
    sentiment: {
      satisfactionScore: 4.0,
      totalSurveyResponses: 1450,
      topPainPoints: [
        { issueKey: 'analytics.pain.public_transport_rarity', count: 680, severity: 'high' },
        { issueKey: 'analytics.pain.bank_friction', count: 540, severity: 'high' },
        { issueKey: 'analytics.pain.language_barrier_jobs', count: 490, severity: 'high' },
      ],
      topAttractions: [
        { factorKey: 'analytics.attract.peace_and_space', count: 1120 },
        { factorKey: 'analytics.attract.low_cost_of_living', count: 960 },
        { factorKey: 'analytics.attract.welcoming_local_community', count: 810 },
      ],
    },
  },
};
