import type { ServiceTicket } from '@/types/serviceRequest';

export const INITIAL_SERVICE_TICKETS: ServiceTicket[] = [
  {
    id: 'ticket-1',
    referenceNumber: 'HEL-2026-4012',
    municipalityId: 'helsinki',
    category: 'daycare_school',
    status: 'in_progress',
    priority: 'high',
    title: 'Bilingual Daycare Placement Inquiry for Kallio / Pasila area',
    description: 'We relocated from Ireland in August and submitted our municipal daycare application for a 3-year-old. We would like to confirm our position on the waiting list and whether English-Finnish bilingual group options are available.',
    createdAt: '2026-09-01T09:30:00Z',
    updatedAt: '2026-09-03T14:15:00Z',
    estimatedResolutionDays: 4,
    assignedDepartment: 'Education & Early Childhood Division (Kasvatuksen ja koulutuksen toimiala)',
    officialResponse: 'Application received and assigned to the district coordinator. A placement offer in daycare Daghemmet / Päiväkoti Alppila is currently being finalized.',
    userEmail: 'resident.mark@example.com',
  },
  {
    id: 'ticket-2',
    referenceNumber: 'ESP-2026-1940',
    municipalityId: 'espoo',
    category: 'housing_permits',
    status: 'resolved',
    priority: 'medium',
    title: 'Resident Parking Zone Permit for Leppävaara district',
    description: 'Need assistance issuing an annual resident parking permit for our family hybrid car registered with Traficom. Online system asked for verification of rental agreement.',
    createdAt: '2026-08-28T11:00:00Z',
    updatedAt: '2026-08-30T10:20:00Z',
    estimatedResolutionDays: 2,
    assignedDepartment: 'Espoo Urban Environment Sector (Kaupunkiympäristö)',
    officialResponse: 'Your rental agreement has been verified against DVV address records. The residential parking zone permit Z-1 has been activated for plate FIN-821.',
    userEmail: 'anna.k@example.com',
  },
  {
    id: 'ticket-3',
    referenceNumber: 'TAM-2026-3081',
    municipalityId: 'tampere',
    category: 'social_integration',
    status: 'under_review',
    priority: 'medium',
    title: 'Integration Plan & Finnish Language Course Voucher for Spouse',
    description: 'My spouse recently arrived on family reunification ties and wants to join the intensive Finnish A1-B1 integration track at Tredu. How can we book an official integration assessment interview?',
    createdAt: '2026-09-05T08:45:00Z',
    updatedAt: '2026-09-06T09:00:00Z',
    estimatedResolutionDays: 5,
    assignedDepartment: 'International House Tampere / Employment Services',
    officialResponse: 'Your request is queued for an advisor at International House Tampere (Rautatienkatu 10). You will receive an SMS invitation for an intake interview.',
    userEmail: 'carlos.m@example.com',
  },
  {
    id: 'ticket-4',
    referenceNumber: 'VAN-2026-0925',
    municipalityId: 'vantaa',
    category: 'waste_environment',
    status: 'resolved',
    priority: 'low',
    title: 'Hazardous Waste & Electronics Collection Truck Schedule (Myyrmäki)',
    description: 'Inquiring when the HSY mobile collection truck (Sortti-keräysauto) will next stop near Myyrmäenraitti for household paint and broken electronics disposal.',
    createdAt: '2026-08-20T16:10:00Z',
    updatedAt: '2026-08-21T11:30:00Z',
    estimatedResolutionDays: 1,
    assignedDepartment: 'HSY Waste Management / City of Vantaa',
    officialResponse: 'The autumn Sortti truck stop is scheduled on Tuesday September 15th from 17:30 to 18:15 at Myyrmäen urheilupuisto parking lot. Service is free of charge.',
    userEmail: 'david.l@example.com',
  },
  {
    id: 'ticket-5',
    referenceNumber: 'TUR-2026-5120',
    municipalityId: 'turku',
    category: 'daycare_school',
    status: 'submitted',
    priority: 'high',
    title: 'Grade 4 Comprehensive School Transfer Inquiry',
    description: 'We are moving from Runosmäki to Kupittaa in October. Our child currently attends an English-stream 4th grade class. Can we transfer enrollment to Turun kansainvälinen koulu (Turku International School)?',
    createdAt: '2026-09-07T13:20:00Z',
    updatedAt: '2026-09-07T13:20:00Z',
    estimatedResolutionDays: 3,
    assignedDepartment: 'Turku City Education Division (Sivistystoimiala)',
    userEmail: 'elena.s@example.com',
  },
  {
    id: 'ticket-6',
    referenceNumber: 'OUL-2026-2188',
    municipalityId: 'oulu',
    category: 'tax_business',
    status: 'under_review',
    priority: 'medium',
    title: 'Consultation with Startup Advisor regarding Oulu Business Subsidies',
    description: 'We are foreign researchers founding a deep-tech robotics startup in Oulu. We would like to schedule a meeting regarding city business incubator space and startup grant (starttiraha) municipal statement.',
    createdAt: '2026-09-06T15:40:00Z',
    updatedAt: '2026-09-07T10:05:00Z',
    estimatedResolutionDays: 3,
    assignedDepartment: 'BusinessOulu International Growth Services',
    officialResponse: 'Business advisor assigned. An invitation to an in-person session at BusinessAsema (Hallituskatu 36) has been dispatched.',
    userEmail: 'viktor.p@example.com',
  },
  {
    id: 'ticket-7',
    referenceNumber: 'HEL-2026-6104',
    municipalityId: 'helsinki',
    category: 'general_inquiry',
    status: 'resolved',
    priority: 'low',
    title: 'Multilingual Public Library Card Registration & Digital Media Access',
    description: 'Can non-EU residents without Finnish online banking credentials (pankkitunnukset) register for a Helmet library card to access Oodi co-working and digital magazines?',
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-08-16T09:40:00Z',
    estimatedResolutionDays: 1,
    assignedDepartment: 'Helmet Libraries Customer Services',
    officialResponse: 'Yes! Simply present a valid passport or official photo ID and proof of residence at any Helmet library service desk. A physical card and PIN will be issued immediately.',
    userEmail: 'sarah.t@example.com',
  },
];
